### ISSUE TITLE
Fix region centering buttons

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/soundcomparisons#244]
Edited by runjak:
Having the region centering buttons on the right side of the menu breaks the layout.
![screenshot_2016-01-14_16-02-40](https://cloud.githubusercontent.com/assets/5417642/12327724/521e6712-bad8-11e5-89dd-1b4eb72f1a80.png)
To mitigate this problem the region centering buttons should be moved to the left side of the menu.

**Comment by runjak** [comment]
This issue is fixed and deployed, but the old template appears to be lingering in the caches of browsers.
When I view the page in private mode the change is addressed as wanted.
In normal mode however the page still uses the outdated templates because they're served from cache.
![screenshot_2016-01-14_15-57-27](https://cloud.githubusercontent.com/assets/5417642/12327594/c0fb106e-bad7-11e5-9a40-07dd09352b31.png)
I'll have a look at the template loader to see if I can ignore caching there.
Other ways to handle this would be to use more explicit caching via `AppCache`,
or to bake the templates into the JavaScript that's served.

**Comment by runjak** [comment]
This will be deployed with the next update on the server, which will happen
either on Monday or when I get my VPN working again, whichever happens first.
